version: '3.9'

services:
  api:
    container_name: nexus_api
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: bash -c "npx prisma migrate dev && yarn start:dev"
    volumes:
      - .:/api

  database:
    container_name: nexus_database
    image: postgres:latest
    hostname: database
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s